// Maps jurisdiction strings from the spreadsheet (including typos, truncated
// cells, and US-state / Canadian-province level entries) to a country name
// and ISO-3 code. The map used for world-map shading rolls sub-national
// jurisdictions up to their parent country.
//
// Keys are lower-cased. If you find new jurisdictions not covered here,
// add a line below and redeploy.

/** @type {Record<string, { country: string; iso3: string }>} */
export const COUNTRY_ALIASES = {
  // === Countries ===
  "argentina": { country: "Argentina", iso3: "ARG" },
  "australia": { country: "Australia", iso3: "AUS" },
  "austria": { country: "Austria", iso3: "AUT" },
  "austrian": { country: "Austria", iso3: "AUT" },
  "bahamas": { country: "Bahamas", iso3: "BHS" },
  "bahrain": { country: "Bahrain", iso3: "BHR" },
  "bangladesh": { country: "Bangladesh", iso3: "BGD" },
  "barbados": { country: "Barbados", iso3: "BRB" },
  "belgium": { country: "Belgium", iso3: "BEL" },
  "belguim": { country: "Belgium", iso3: "BEL" },
  "belize": { country: "Belize", iso3: "BLZ" },
  "bermuda": { country: "Bermuda", iso3: "BMU" },
  "brazil": { country: "Brazil", iso3: "BRA" },
  "british virgin islands": { country: "British Virgin Islands", iso3: "VGB" },
  "cayman islands": { country: "Cayman Islands", iso3: "CYM" },
  "chile": { country: "Chile", iso3: "CHL" },
  "china": { country: "China", iso3: "CHN" },
  "cook islands": { country: "Cook Islands", iso3: "COK" },
  "cyprus": { country: "Cyprus", iso3: "CYP" },
  "denmark": { country: "Denmark", iso3: "DNK" },
  "dominican republic": { country: "Dominican Republic", iso3: "DOM" },
  "republica dominica": { country: "Dominican Republic", iso3: "DOM" },
  "egypt": { country: "Egypt", iso3: "EGY" },
  "estonia": { country: "Estonia", iso3: "EST" },
  "ethiopia": { country: "Ethiopia", iso3: "ETH" },
  "fiji": { country: "Fiji", iso3: "FJI" },
  "finland": { country: "Finland", iso3: "FIN" },
  "france": { country: "France", iso3: "FRA" },
  "georgia": { country: "Georgia", iso3: "GEO" },
  "germany": { country: "Germany", iso3: "DEU" },
  "german": { country: "Germany", iso3: "DEU" },
  "ghana": { country: "Ghana", iso3: "GHA" },
  "gibraltar": { country: "Gibraltar", iso3: "GIB" },
  "grenada": { country: "Grenada", iso3: "GRD" },
  "guernsey": { country: "Guernsey", iso3: "GGY" },
  "hong kong": { country: "Hong Kong", iso3: "HKG" },
  "hong kong sar": { country: "Hong Kong", iso3: "HKG" },
  "hungary": { country: "Hungary", iso3: "HUN" },
  "india": { country: "India", iso3: "IND" },
  "indonesia": { country: "Indonesia", iso3: "IDN" },
  "ireland": { country: "Ireland", iso3: "IRL" },
  "isle of man": { country: "Isle of Man", iso3: "IMN" },
  "italy": { country: "Italy", iso3: "ITA" },
  "ivory coast": { country: "Côte d'Ivoire", iso3: "CIV" },
  "jamaica": { country: "Jamaica", iso3: "JAM" },
  "japan": { country: "Japan", iso3: "JPN" },
  "jersey": { country: "Jersey", iso3: "JEY" },
  "kenya": { country: "Kenya", iso3: "KEN" },
  "kiribati": { country: "Kiribati", iso3: "KIR" },
  "korea": { country: "South Korea", iso3: "KOR" },
  "south korea": { country: "South Korea", iso3: "KOR" },
  "latvia": { country: "Latvia", iso3: "LVA" },
  "liberia": { country: "Liberia", iso3: "LBR" },
  "liechtenstein": { country: "Liechtenstein", iso3: "LIE" },
  "lithuania": { country: "Lithuania", iso3: "LTU" },
  "luxembourg": { country: "Luxembourg", iso3: "LUX" },
  "malawi": { country: "Malawi", iso3: "MWI" },
  "malaysia": { country: "Malaysia", iso3: "MYS" },
  "maldives": { country: "Maldives", iso3: "MDV" },
  "mali": { country: "Mali", iso3: "MLI" },
  "malta": { country: "Malta", iso3: "MLT" },
  "marshall islands": { country: "Marshall Islands", iso3: "MHL" },
  "mauritius": { country: "Mauritius", iso3: "MUS" },
  "mexico": { country: "Mexico", iso3: "MEX" },
  "mexico fed": { country: "Mexico", iso3: "MEX" },
  "micronesia": { country: "Micronesia", iso3: "FSM" },
  "myanmar": { country: "Myanmar", iso3: "MMR" },
  "namibia": { country: "Namibia", iso3: "NAM" },
  "nauru": { country: "Nauru", iso3: "NRU" },
  "netherlands": { country: "Netherlands", iso3: "NLD" },
  "netherlan": { country: "Netherlands", iso3: "NLD" },
  "natherlands": { country: "Netherlands", iso3: "NLD" },
  "new zealand": { country: "New Zealand", iso3: "NZL" },
  "new zeala": { country: "New Zealand", iso3: "NZL" },
  "nigeria": { country: "Nigeria", iso3: "NGA" },
  "niue": { country: "Niue", iso3: "NIU" },
  "oman": { country: "Oman", iso3: "OMN" },
  "palau": { country: "Palau", iso3: "PLW" },
  "papua new guinea": { country: "Papua New Guinea", iso3: "PNG" },
  "philippines": { country: "Philippines", iso3: "PHL" },
  "poland": { country: "Poland", iso3: "POL" },
  "portugal": { country: "Portugal", iso3: "PRT" },
  "puerto rico": { country: "Puerto Rico", iso3: "PRI" },
  "qatar": { country: "Qatar", iso3: "QAT" },
  "republic of congo": { country: "Republic of the Congo", iso3: "COG" },
  "rwanda": { country: "Rwanda", iso3: "RWA" },
  "saint kitts and nevis": { country: "Saint Kitts and Nevis", iso3: "KNA" },
  "samoa": { country: "Samoa", iso3: "WSM" },
  "saudi arabia": { country: "Saudi Arabia", iso3: "SAU" },
  "serbia": { country: "Serbia", iso3: "SRB" },
  "seychelles": { country: "Seychelles", iso3: "SYC" },
  "singapore": { country: "Singapore", iso3: "SGP" },
  "slovakia": { country: "Slovakia", iso3: "SVK" },
  "slovenia": { country: "Slovenia", iso3: "SVN" },
  "solomon islands": { country: "Solomon Islands", iso3: "SLB" },
  "somalia": { country: "Somalia", iso3: "SOM" },
  "south africa": { country: "South Africa", iso3: "ZAF" },
  "spain": { country: "Spain", iso3: "ESP" },
  "suriname": { country: "Suriname", iso3: "SUR" },
  "sweden": { country: "Sweden", iso3: "SWE" },
  "switzerland": { country: "Switzerland", iso3: "CHE" },
  "swizerland": { country: "Switzerland", iso3: "CHE" },
  "taiwan": { country: "Taiwan", iso3: "TWN" },
  "tanzania": { country: "Tanzania", iso3: "TZA" },
  "thailand": { country: "Thailand", iso3: "THA" },
  "tonga": { country: "Tonga", iso3: "TON" },
  "trinidad and tobago": { country: "Trinidad and Tobago", iso3: "TTO" },
  "turkey": { country: "Türkiye", iso3: "TUR" },
  "turkiye": { country: "Türkiye", iso3: "TUR" },
  "tuvalu": { country: "Tuvalu", iso3: "TUV" },
  "uganda": { country: "Uganda", iso3: "UGA" },
  "united arab emirates": { country: "United Arab Emirates", iso3: "ARE" },
  "abu dhabi uea": { country: "United Arab Emirates", iso3: "ARE" },
  "dubai uea": { country: "United Arab Emirates", iso3: "ARE" },
  "united kingdom": { country: "United Kingdom", iso3: "GBR" },
  "uk": { country: "United Kingdom", iso3: "GBR" },
  "united states": { country: "United States", iso3: "USA" },
  "united states of america": { country: "United States", iso3: "USA" },
  "us fed": { country: "United States", iso3: "USA" },
  "vanuatu": { country: "Vanuatu", iso3: "VUT" },
  "vietnam": { country: "Vietnam", iso3: "VNM" },
  "zambia": { country: "Zambia", iso3: "ZMB" },
  "zimbabwe": { country: "Zimbabwe", iso3: "ZWE" },

  // === EU / supranational — show on map as "no country" but keep listed ===
  "eu": { country: "European Union", iso3: null },
  "european union": { country: "European Union", iso3: null },
  "international": { country: "International", iso3: null },
  "north ame": { country: "North America", iso3: null },
  "egmont": { country: "International (Egmont Group)", iso3: null },

  // === US states → United States ===
  "alabama": { country: "United States", iso3: "USA" },
  "alaska": { country: "United States", iso3: "USA" },
  "arizona": { country: "United States", iso3: "USA" },
  "arkansas": { country: "United States", iso3: "USA" },
  "california": { country: "United States", iso3: "USA" },
  "colorado": { country: "United States", iso3: "USA" },
  "connecticut": { country: "United States", iso3: "USA" },
  "delaware": { country: "United States", iso3: "USA" },
  "district of columbia": { country: "United States", iso3: "USA" },
  "florida": { country: "United States", iso3: "USA" },
  "hawaii": { country: "United States", iso3: "USA" },
  "idaho": { country: "United States", iso3: "USA" },
  "illinois": { country: "United States", iso3: "USA" },
  "indiana": { country: "United States", iso3: "USA" },
  "iowa": { country: "United States", iso3: "USA" },
  "kansas": { country: "United States", iso3: "USA" },
  "kentucky": { country: "United States", iso3: "USA" },
  "louisiana": { country: "United States", iso3: "USA" },
  "maine": { country: "United States", iso3: "USA" },
  "maryland": { country: "United States", iso3: "USA" },
  "massachusetts": { country: "United States", iso3: "USA" },
  "michigan": { country: "United States", iso3: "USA" },
  "minnesota": { country: "United States", iso3: "USA" },
  "mississippi": { country: "United States", iso3: "USA" },
  "missouri": { country: "United States", iso3: "USA" },
  "montana": { country: "United States", iso3: "USA" },
  "nebraska": { country: "United States", iso3: "USA" },
  "nevada": { country: "United States", iso3: "USA" },
  "nevada de": { country: "United States", iso3: "USA" },
  "nevada se": { country: "United States", iso3: "USA" },
  "new hampshire": { country: "United States", iso3: "USA" },
  "new hamps": { country: "United States", iso3: "USA" },
  "new jersey": { country: "United States", iso3: "USA" },
  "new jerse": { country: "United States", iso3: "USA" },
  "new mexico": { country: "United States", iso3: "USA" },
  "new mexic": { country: "United States", iso3: "USA" },
  "new york": { country: "United States", iso3: "USA" },
  "north carolina": { country: "United States", iso3: "USA" },
  "north dakota": { country: "United States", iso3: "USA" },
  "ohio": { country: "United States", iso3: "USA" },
  "ohio depa": { country: "United States", iso3: "USA" },
  "oklahoma": { country: "United States", iso3: "USA" },
  "oregon": { country: "United States", iso3: "USA" },
  "pennsylvania": { country: "United States", iso3: "USA" },
  "rhode island": { country: "United States", iso3: "USA" },
  "south carolina": { country: "United States", iso3: "USA" },
  "south dakota": { country: "United States", iso3: "USA" },
  "tennessee": { country: "United States", iso3: "USA" },
  "texas": { country: "United States", iso3: "USA" },
  "utah": { country: "United States", iso3: "USA" },
  "vermont": { country: "United States", iso3: "USA" },
  "virginia": { country: "United States", iso3: "USA" },
  "washington": { country: "United States", iso3: "USA" },
  "west virginia": { country: "United States", iso3: "USA" },
  "wisconsin": { country: "United States", iso3: "USA" },
  "wyoming": { country: "United States", iso3: "USA" },

  // === Canadian provinces → Canada ===
  "canada": { country: "Canada", iso3: "CAN" },
  "canada fed": { country: "Canada", iso3: "CAN" },
  "alberta": { country: "Canada", iso3: "CAN" },
  "british columbia": { country: "Canada", iso3: "CAN" },
  "ontario": { country: "Canada", iso3: "CAN" },
  "québec": { country: "Canada", iso3: "CAN" },
  "quebec": { country: "Canada", iso3: "CAN" },
};
